### ISSUE TITLE
Valid HTML test not passing

### ISSUE THREAD

**Issue by yuriehong** [learn-co-curriculum/phase-0-html-document-structure-lab#23]
### Canvas Link

https://learning.flatironschool.com/courses/5729/assignments/179061?module_item_id=395748

### Concern

My code for the "document structure continued" assignment continues to fail the last test for valid html structure. I have copied my code into the validator (https://validator.w3.org/nu/#textarea) and it says no errors to show, so I am confused why the last test continues to fail.

### Additional Context

![image](https://user-images.githubusercontent.com/54913649/174403090-c11299a7-d5ec-45e9-99b8-990bc22eb0be.png)

**Comment by lizbur10** [comment]
Hi @yuriehong! Your code definitely looks good, but if you scroll down a little farther in your terminal output and look at the actual error, you should see what the issue is:

<img width="577" alt="Screen Shot 2022-07-01 at 12 17 51 PM" src="https://user-images.githubusercontent.com/9666939/176932630-1d14109a-7796-4add-8694-53248e8b051b.png">

If you still need help with this, I suggest that you use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.
